---
- name: Create 'acmetiny' user
  user: >
    name=acmetiny shell=/usr/sbin/nologin home=/etc/acmetiny
    system=yes createhome=no

- name: Create /etc/acmetiny
  file: >
    path=/etc/acmetiny/challenges state=directory recurse=yes
    owner=root group=acmetiny mode=0775

# generate Let's Encrypt account key
- include: genkey.yml
  vars:
    path: "/etc/acmetiny/account.key"
    owner: "root"
    group: "acmetiny"
    mode: "0640"

# generate SSL private key
- include: genkey.yml
  vars:
    path: "/etc/ssl/private/nginx.key"
    owner: "root"
    group: "root"
    mode: "0600"

- name: Generate CSR config file
  template: src=csr.j2 dest=/etc/acmetiny/openssl.cnf
  register: csr_config

- name: Generate Certificate Signing Request
  command: >
    /usr/bin/openssl req -new
    -out /etc/acmetiny/letsencrypt.csr
    -key /etc/ssl/private/nginx.key
    -config /etc/acmetiny/openssl.cnf
  when: csr_config.changed

- name: Generate self-signed initial nginx certificate
  command: >
    /usr/bin/openssl x509
    -in /etc/acmetiny/letsencrypt.csr
    -out /etc/ssl/nginx.pem
    -req -signkey /etc/ssl/private/nginx.key -days 30
  args:
    creates: /etc/ssl/nginx.pem

- name: Download acme_tiny.py
  get_url: >
    url=https://github.com/diafygi/acme-tiny/raw/{{acmetiny_rev}}/acme_tiny.py
    dest=/etc/acmetiny/acme_tiny.py mode=0755

- name: Download Let's Encrypt intermediate certificate
  get_url:
    url=https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem
    dest=/etc/ssl/letsencrypt-x3.pem mode=0644

- name: Install acmetiny_renew.sh
  copy: >
    src=acmetiny_renew.sh
    dest=/etc/acmetiny/acmetiny_renew.sh
    mode=0755

- name: Install acmetiny systemd timer unit
  copy: src={{item}} dest=/etc/systemd/system/{{item}}
  register: acmetiny_service
  with_items:
    - acmetiny.service
    - acmetiny.timer

- name: Reload systemd deamon
  systemd: daemon_reload=yes
  when: acmetiny_service.changed

- name: Renew certificates
  systemd:
    name: acmetiny
    state: started
  when: csr_config.changed

- name: Enable monthly timer for certificate renewal
  systemd:
    name: acmetiny.timer
    state: started
    enabled: True

- name: Copy nginx HTTPS configuration file
  copy: src=https.conf dest=/etc/nginx/site.d/https.conf
  notify: reload nginx
