---
- name: Install PHP 7
  apt: name=php7.0-fpm state=latest update_cache=yes

- name: Start PHP fastcgi workers
  service: name=php7.0-fpm state=started enabled=yes

- name: Configure Nginx for PHP
  template: src={{item.src}} dest={{item.dest}}
  with_items:
   - { src: 'fastcgi.conf', dest: '/etc/nginx/fastcgi.conf' }
   - { src: 'php7.conf',    dest: '/etc/nginx/php7.conf' }
  notify: reload nginx
