---
- name: Add dotdeb repository key
  apt_key: url=https://www.dotdeb.org/dotdeb.gpg

- name: Add dotdeb repository
  apt_repository: repo='{{item}} {{ansible_distribution_release}} all'
  with_items:
   - 'deb http://packages.dotdeb.org'
   - 'deb-src http://packages.dotdeb.org'

- name: Install nginx
  apt: name=nginx-light=1.8.* state=present update_cache=yes

- name: Copy nginx configuration files
  template: src={{item.src}} dest={{item.dest}}
  with_items:
   - { src: 'nginx.conf',   dest: '/etc/nginx/nginx.conf' }
   - { src: 'mime.types',   dest: '/etc/nginx/mime.types' }
   - { src: 'default.conf', dest: '/etc/nginx/conf.d/default.conf' }

- name: Remove unused nginx config files
  file: path={{item}} state=absent
  with_items:
   - /etc/nginx/fastcgi.conf
   - /etc/nginx/fastcgi_params
   - /etc/nginx/koi-utf
   - /etc/nginx/koi-win
   - /etc/nginx/naxsi_core.rules
   - /etc/nginx/naxsi.rules
   - /etc/nginx/proxy_params
   - /etc/nginx/scgi_params
   - /etc/nginx/uwsgi_params
   - /etc/nginx/win-utf
   - /etc/nginx/sites-available/
   - /etc/nginx/sites-enabled/
   - /etc/nginx/snippets/
  notify: reload nginx
