---
- name: Add dotdeb repository key
  apt_key: url=https://www.dotdeb.org/dotdeb.gpg

- name: Add dotdeb repository
  apt_repository: repo='{{item}} {{ansible_distribution_release}} all'
  with_items:
   - 'deb http://packages.dotdeb.org'
   - 'deb-src http://packages.dotdeb.org'

- name: Install nginx
  apt: name=nginx-light=1.8.* state=present update_cache=yes
  notify: undo nginx postinst

- name: Copy nginx configuration files
  template: src={{item.src}} dest={{item.dest}}
  with_items:
   - { src: 'nginx.conf',   dest: '/etc/nginx/nginx.conf' }
   - { src: 'mime.types',   dest: '/etc/nginx/mime.types' }
#   - { src: 'default.conf', dest: '/etc/nginx/conf.d/default.conf' }
  notify: reload nginx
