---
- name: Add dotdeb repository key
  apt_key: url=https://www.dotdeb.org/dotdeb.gpg

- name: Add dotdeb repository
  apt_repository: repo='{{item}} {{ansible_distribution_release}} all'
  with_items:
   - 'deb http://packages.dotdeb.org'
   - 'deb-src http://packages.dotdeb.org'

- name: Install nginx
  apt: name=nginx-light=1.12.* state=present update_cache=yes

- name: Undo nginx `postinst` configuration
  script: nginx-undo-postinst.sh

- name: Create /etc/nginx subdirectories
  file: path={{item}} state=directory
  with_items:
    - /etc/nginx/conf.d
    - /etc/nginx/site.d

- name: Copy nginx configuration files
  template: src={{item.src}} dest={{item.dest}}
  with_items:
   - { src: 'nginx.conf', dest: '/etc/nginx/nginx.conf' }
   - { src: 'mime.types', dest: '/etc/nginx/mime.types' }
   - { src: 'conf.d/{{nginx_default_conf}}',
       dest: '/etc/nginx/conf.d/default.conf' }
  notify: reload nginx
