---
- name: Add dotdeb repository key
  apt_key: url=https://www.dotdeb.org/dotdeb.gpg

- name: Add dotdeb repository
  apt_repository: repo='{{item}} {{ansible_distribution_release}} all'
  with_items:
   - 'deb http://packages.dotdeb.org'
   - 'deb-src http://packages.dotdeb.org'

# the following installs the nginx binary and creates the 'nginx' user
- name: Install nginx
  apt: name=nginx-light=1.8.* state=present update_cache=yes

# overwrite the installed configuration files with our own defaults
- name: Write static nginx files
  synchronize: > 
    src=nginx dest=/etc/ recursive=yes delete=yes
    archive=no checksum=yes rsync_opts="--exclude=*~"
  notify: reload nginx
